services:
  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data:/var/www/html/data
      - ./html:/var/www/html
    ports:
      - 127.0.0.1:${PORT:-8080}:80
    environment:
      - VIRTUAL_HOST=${APP_HOSTNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_HOST=${REDIS_HOST}
  db:
    image: mariadb:10.11
    restart: always
    profiles: [withdb]
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always
    profiles: [withredis]

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./html:/var/www/html
    entrypoint: /cron.sh
